---
title: "Invert Sampling Cleaning"
author: "Chris Kracha"
date: "2023-01-28"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
library(vegan)
library("hydroTSM")
```

# load in tables
```{r message=FALSE}
inv2018csv <- read_csv("downloaded tables/2018_raw_normalized.csv", skip = 5)
inv2019csv <- read_csv("downloaded tables/2019_normalized.csv", skip = 1)
inv2021_22csv <- read_csv("downloaded tables/2021_raw.csv")
```

# format tables for each year
```{r}
inv2018f <- inv2018csv %>% clean_names() %>% 
  # get relevant columns
  select(1:42, -4) %>%
  # keep only the rows with dates
  filter(!is.na(date_1)) %>%
  # select normalized columns
  select(1:3, ends_with("_number_liter")) %>%
  # remove _number_liter from names
  rename_with(~ gsub("_number_liter", "", .x)) %>%
  # replace species NAs with zeroes
  mutate(across(ostracod:amphipod, ~replace_na(.,0)),
          # format date
         date_1 = dmy(date_1))

inv2019f <- inv2019csv %>% clean_names() %>% 
  select(1:42, -4, -total_number) %>% 
  # keep only the rows with dates
  filter(!is.na(date_1), !is.na(site_2)) %>%
  # make species numeric
  mutate(across(ostracod:clam_shrimp, ~as.numeric(.)),
         # replace species NAs with zeroes
         across(ostracod:clam_shrimp, ~replace_na(.,0)),
         # format date
         date_1 = dmy(date_1))

inv2021f <- inv2021_22csv %>% clean_names() %>%
  # remove unused variables
  select(-person_entering_data, -person_that_sorted_the_sample, 
         -total_number, -unknown, -x57, -comments) %>% 
  # remove unfinished samples
  filter(!row_number() %in% c(7, 24, 26)) %>%
  # replace species NAs with zeroes
  mutate(across(ostracod:larvae, ~replace_na(.,0)),
         # normalize species counts by liter
         across(ostracod:larvae, ~.x/7.5),
         # make species numeric
         across(ostracod:larvae, ~as.numeric(.)),
         # format date
         date_on_vial = dmy(date_on_vial))
inv2021f[7, 5] <- (inv2021f[7, 5])/10 # fix probable error ??
```

# rename columns to match
```{r}
# rename columns to match order_family format
inv2018 <- inv2018f %>% 
  rename(date = date_1,
         site = site_2,
         sample_type = sample_type_3,
         # add order to names
         hemiptera_corixidae_boatman = corixidae_boatman,
         diptera_chironomid = chironomid,
         diptera_ceratopogonidae = ceratopogonidae,
         diptera_ephydridae = ephydridae,
         diptera_stratiomyidae = stratiomyidae,
         diptera_culicidae = culicidae,
         arachnida_acari = mile, # misspell
         hemiptera_notonectidae = heteroptera_backswimmer,
         coleoptera_sp = aquatic_coleoptera_sp,
         coleoptera_hydrophilidae = coleoptera_hydrophilidae_biter,
         coleoptera_hydraenidae = coleoptera_hydraenidae_stripes,
         coleoptera_dytiscidae = coleoptera_dystiscidae) # fix spelling

inv2019 <- inv2019f %>% 
  rename(date = date_1,
         site = site_2,
         sample_type = sample_type_3,
         ephemeroptera = ephemeroptera_sp, # sp is only category
         arachnida_acari = arachnida_acari_mite,
         coleoptera_hydraenidae = coleoperta_hydraenidae)

inv2021 <- inv2021f %>% 
  rename(date = date_on_vial,
         diptera_syrphidae = syrphidae,
         plecoptera = plecoptera_sp, # sp is only category
         diptera_ceratopogonidae = diptera_ceratopohonidae,
         coleoptera_hydraenidae = coleoperta_hydraenidae)
```

# combine columns and fix factors
```{r}
# combine rows
inv <- bind_rows(inv2018, inv2019, inv2021) %>%
  # standardize sample_type column
  mutate(sample_type = case_when(sample_type %in% c("FB", "FB 250") ~ "FB250", # change FB and FB 250 to FB250
                                 str_detect(sample_type, "CORE") ~ "CORE", # change anything with CORE to just CORE
                                 TRUE ~ sample_type), # keep the rest
         ## standardize site column
         site = case_when(site == "NPB 2" ~ "NPB2",
                          site %in% c("NEV", "NWC") ~ "NEC", # assumed typos
                          site == "CVP1" ~ "VP1",
                          site == "VNVP2" ~ "NVP2", 
                          site == "VNVP4" ~ "NVP4",
                          TRUE ~ site),
         # add site_type NCOS/COPR column
         site_type = case_when(site %in% c("CUL1", "MO1", "NDC", "NEC", "NMC", "NPB", 
                                           "NPB1", "NPB2", "NVBR", "NWP", "PIER", "VBR1") ~ "slough",
                               TRUE ~ "pool"),
         # add seasons column
         season = time2season(date, out.fmt = "seasons"), 
         season = as.factor(case_when(season == "autumm" ~ "fall", # rename factor
                            TRUE ~ season)),
         season = factor(season, c("fall", "winter", "spring", "summer"))) %>% # reorder seasons
  
  # reorder columns to make sense
  select(date, season, site, site_type, sample_type, ostracod, copepod, amphipod, isopod, cladocera, clam_shrimp, annelida_sp, annelida_oligochaete, annelida_polychaete, nematode, mollusk, gastropod_snail, coleoptera_sp, coleoptera_hydrophilidae, coleoptera_tropiscernus, coleoptera_dytiscidae, coleoptera_dytiscidae_agabus, coleoptera_dytiscidae_liodessus_affinis, coleoptera_dytiscidae_colymbetinae, coleoptera_hydraenidae, coleoptera_hydraenidae_larva_joe, coleoptera_curculionidae_weavil, coleoptera_gyrindae_gyrinini, dipteran_sp, diptera_chironomid, diptera_ceratopogonidae, diptera_ephydridae, diptera_stratiomyidae, diptera_culicidae, diptera_syrphidae, tipulidae_larva, ephemeroptera, ephemeroptera_sp, plecoptera, trichoptera_sp, hemiptera_corixidae_boatman, hemiptera_notonectidae, hemiptera_mesoveliidae, odonate, collembola_springtail, lepidoptera_crambidae, arachnida_acari, arachnida_acari_mite, hydrachnidia, larvae, terrestrials)

# get list of columns with no IDs
inv[, 6:length(inv)] %>% select_if(colSums(., na.rm = T) != 0) %>% colnames() %>% 
  setdiff(colnames(inv[, 6:length(inv)]), .)

inv %>% write.csv("cleaned tables/all_invert_data.csv")

rm(inv2018csv, inv2019csv, inv2021_22csv, inv2018f, inv2019f, inv2021f)
```

# make totals table
```{r}

# very roughly ordered from tolerant to sensitive
invTotal <- inv %>% 
  rowwise() %>%
  mutate(flies = sum(c_across(dipteran_sp:diptera_syrphidae), na.rm = T),
         boaters = sum(c_across(hemiptera_corixidae_boatman:hemiptera_mesoveliidae), na.rm = T),
         mites = sum(c_across(arachnida_acari:hydrachnidia), na.rm = T),
         crustaceans = sum(c_across(ostracod:clam_shrimp), na.rm = T),
         worms = sum(c_across(annelida_sp:nematode), na.rm = T),
         mollusks = sum(c_across(mollusk:gastropod_snail), na.rm = T),
         beetles = sum(c_across(coleoptera_sp:coleoptera_gyrindae_gyrinini), na.rm = T),
         springtail = collembola_springtail,
         dragonfly = odonate,
         larvae = sum(c_across(c(tipulidae_larva, larvae)), na.rm = T),
         ept = sum(c_across(ephemeroptera:trichoptera_sp), na.rm = T),
         total = sum(c_across(ostracod:terrestrials), na.rm = T)) %>%
  select(date:sample_type, flies, boaters, mites, crustaceans, worms, mollusks, 
         beetles, springtail, dragonfly, larvae, ept, total)

invTotal %>% write.csv("cleaned tables/all_invert_data_totals.csv")
```

# make long tables
```{r}
invLong <- inv %>% pivot_longer(6:length(inv), 
                                names_to = "taxa", 
                                values_to = "organisms_L") %>%
  mutate(taxa = as.factor(taxa)) %>% na.omit()

invLong %>% write.csv("cleaned tables/all_invert_data_long.csv")


invTotalLong <- invTotal %>% select(-total) %>% pivot_longer(6:(length(invTotal)-1), 
                                                            names_to = "group", 
                                                            values_to = "organisms_L") %>%
  mutate(group = fct_relevel(as.factor(group), c('flies', 'boaters', 'mites', 'crustaceans', 'worms', 
                                                 'mollusks', 'beetles', 'springtail', 'dragonfly', 
                                                 'larvae', 'ept'))) %>% na.omit()

invTotalLong %>% write.csv("cleaned tables/all_invert_data_totals_long.csv")
```

# visualize data coverages
```{r}
ggplot(invLong, aes(fill = site_type, y = organisms_L, x = season)) + geom_bar(stat = "identity") +
  ggtitle("Organisms collected by season") + ylab("organisms/L") + labs(fill = "site location")

ggplot(inv, aes(fill = site_type, x = season)) + geom_bar(stat = "count") +
  ggtitle("Samples collected by season") + ylab("sample count") + labs(fill = "site location")

ggplot(invLong, aes(fill = sample_type, y = organisms_L, x = year(date))) + geom_bar(stat = "identity") +
  ggtitle("Organisms collected by year") + ylab("organisms/L") + labs(fill = "sample type")

ggplot(inv, aes(fill = sample_type, x = year(date))) + geom_bar(stat = "count") +
  ggtitle("Samples collected by year") + ylab("sample count") + labs(fill = "sample type")

ggplot(inv, aes(x = date, y = site, color = sample_type)) + geom_point(shape = 15) +
  ggtitle("Samples by site and date") + labs(color = "sample type")
```

# visualize organisms
```{r}
# visualize filter beaker organisms from slough
invTotalLong %>% filter(sample_type == "FB250", site_type == "slough") %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by slough site, filter beaker method") + ylab("organisms/L") + labs(fill = "taxa group")

invTotalLong %>% filter(sample_type == "FB250", site_type == "slough", group != "crustaceans") %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by slough site, filter beaker method \nNo crustaceans") + ylab("organisms/L") + labs(fill = "taxa group")

invTotalLong %>% filter(sample_type == "FB250", site_type == "slough", !(group %in% c("crustaceans", "boaters"))) %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by slough site, filter beaker method \nNo crustaceans or boaters") + 
  ylab("organisms/L") + labs(fill = "taxa group")

invTotalLong %>% filter(sample_type == "FB250", site_type == "slough", !(group %in% c("crustaceans", "boaters", "flies"))) %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by slough site, filter beaker method \nNo crustaceans, boaters, or flies") + 
  ylab("organisms/L") + labs(fill = "taxa group")

# visualize core organisms from slough
invTotalLong %>% filter(sample_type == "CORE", site_type == "slough") %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by slough site, sediment core method") + ylab("organisms/L") + labs(fill = "taxa group")

invTotalLong %>% filter(sample_type == "CORE", site_type == "slough", group != "crustaceans") %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by slough site, sediment core method \nNo crustaceans") + ylab("organisms/L") + labs(fill = "taxa group")

invTotalLong %>% filter(sample_type == "CORE", site_type == "slough", !(group %in% c("crustaceans", "boaters"))) %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by slough site, sediment core method \nNo crustaceans or boaters") + 
  ylab("organisms/L") + labs(fill = "taxa group")

# visualize filter beaker organisms from vernal pools
invTotalLong %>% filter(sample_type == "FB250", site_type == "pool") %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by vernal pool, filter beaker method") + ylab("organisms/L") + labs(fill = "taxa group")

invTotalLong %>% filter(sample_type == "FB250", site_type == "pool", !(group %in% c("crustaceans"))) %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by vernal pool, filter beaker method \nNo crustaceans") + ylab("organisms/L") + labs(fill = "taxa group")

# visualize core organisms from vernal pools
invTotalLong %>% filter(sample_type == "CORE", site_type == "pool") %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by vernal pool, sediment core method") + ylab("organisms/L") + labs(fill = "taxa group")

invTotalLong %>% filter(sample_type == "CORE", site_type == "pool", !(group %in% c("crustaceans"))) %>%
  ggplot(aes(x = site, y = organisms_L, fill = group)) + geom_bar(stat = "identity") +
  ggtitle("Taxa group by vernal pool, sediment core method \nNo crustaceans") + ylab("organisms/L") + labs(fill = "taxa group")
```


